//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.FirefoxBookmark.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.FirefoxBookmark.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL (Ctrl+C).
        /// </summary>
        internal static string context_copy_url {
            get {
                return ResourceManager.GetString("context_copy_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window (Ctrl+N).
        /// </summary>
        internal static string context_open_new {
            get {
                return ResourceManager.GetString("context_open_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in private window (Ctrl+P).
        /// </summary>
        internal static string context_open_private {
            get {
                return ResourceManager.GetString("context_open_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Firefox Bookmark.
        /// </summary>
        internal static string plugin_desc {
            get {
                return ResourceManager.GetString("plugin_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox Bookmark.
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser name.
        /// </summary>
        internal static string settings_browser_name {
            get {
                return ResourceManager.GetString("settings_browser_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name that can be used in Win+R.
        /// </summary>
        internal static string settings_browser_name_desc {
            get {
                return ResourceManager.GetString("settings_browser_name_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path after %APPDATA%, check about:profiles.
        /// </summary>
        internal static string settings_profile_desc {
            get {
                return ResourceManager.GetString("settings_profile_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to "Profiles" folder.
        /// </summary>
        internal static string settings_profile_path {
            get {
                return ResourceManager.GetString("settings_profile_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore bookmarklets.
        /// </summary>
        internal static string settings_ignore_bookmarklets {
            get {
                return ResourceManager.GetString("settings_ignore_bookmarklets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks that starts with "javascript:".
        /// </summary>
        internal static string settings_ignore_bookmarklets_desc {
            get {
                return ResourceManager.GetString("settings_ignore_bookmarklets_desc", resourceCulture);
            }
        }
    }
}
